# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
    { id = "check-added-large-files" },
    { id = "check-case-conflict" },
    { id = "check-json" },
    { id = "check-merge-conflict" },
    { id = "check-toml" },
    { id = "check-yaml" },
    { id = "end-of-file-fixer" },
    { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "runic"
name = "runic"
description = "Format Julia code"
entry = "pixi run julia --project=utils/formatting --startup-file=no --module Runic"
args = [
  "--docstrings",
  "--diff",
  "--inplace"
]
language = "system"
types = ["julia"]

[[repos.hooks]]
id = "typos"
name = "fix typos"
description = "Fix spelling mistakes"
language = "system"
entry = "pixi run typos"
args =["--write-changes", "--force-exclude"]
types = ["text"]
stages = ["pre-commit", "pre-merge-commit", "pre-push", "manual"]
