---
title: Download example models
---

For each wflow Model a test model is available that can help to understand the data
requirements and the usage of each Model. The TOML configuration file per available model are
listed in the Table below:

|  model  | TOML configuration file |
|:--------------- | ------------------|
| wflow\_sbm + kinematic wave | [sbm_config.toml](https://raw.githubusercontent.com/Deltares/Wflow.jl/master/Wflow/test/sbm_config.toml) |
| wflow\_sbm + groundwater flow | [sbm\_gwf\_piave\_demand\_config.toml](https://raw.githubusercontent.com/Deltares/Wflow.jl/master/Wflow/test/sbm_gwf_piave_demand_config.toml) |
| wflow_sediment | [sediment_config.toml](https://raw.githubusercontent.com/Deltares/Wflow.jl/master/Wflow/test/sediment_config.toml) |

The associated Model files (input static, forcing and state files) can easily be downloaded and
for this we share the following Julia code (per Model) that downloads the required files to
your current working directory. For running these test model see also [Usage](./running_wflow.qmd#running-a-simulation)
and [Command Line Interface](./running_wflow.qmd#using-the-command-line-interface).

## wflow\_sbm + kinematic wave
```julia
# urls to TOML and netCDF of the Moselle example model
toml_url = "https://raw.githubusercontent.com/Deltares/Wflow.jl/master/Wflow/test/sbm_config.toml"
staticmaps = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/staticmaps-moselle.nc"
forcing = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/forcing-moselle.nc"
instates = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/instates-moselle.nc"

# create a "data/input" directory in the current directory
testdir = @__DIR__
inputdir = joinpath(testdir, "data/input")
isdir(inputdir) || mkpath(inputdir)
toml_path = joinpath(testdir, "sbm_config.toml")

# download resources to current and input directories
download(staticmaps, joinpath(inputdir, "staticmaps-moselle.nc"))
download(forcing, joinpath(inputdir, "forcing-moselle.nc"))
download(instates, joinpath(inputdir, "instates-moselle.nc"))
download(toml_url, toml_path)
```

## wflow\_sbm + groundwater flow
```julia
# urls to TOML and netCDF of the Piave example model
toml_url = "https://raw.githubusercontent.com/Deltares/Wflow.jl/master/Wflow/test/sbm_gwf_piave_demand_config.toml"
staticmaps = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/staticmaps-piave.nc"
forcing = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/forcing-piave.nc"
instates = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/instates-piave-gwf.nc"

# create a "data/input" directory in the current directory
testdir = @__DIR__
inputdir = joinpath(testdir, "data/input")
isdir(inputdir) || mkpath(inputdir)
toml_path = joinpath(@testdir, "sbm_gwf_piave_demand_config.toml")

# download resources to current and data dirs
download(staticmaps, joinpath(inputdir, "staticmaps-piave.nc"))
download(forcing, joinpath(inputdir, "forcing-piave.nc"))
download(instates, joinpath(inputdir, "instates-piave-gwf.nc"))
download(toml_url, toml_path)
```

## wflow\_sediment
```julia
# urls to TOML and netCDF of the Moselle example model
toml_url = "https://raw.githubusercontent.com/Deltares/Wflow.jl/master/Wflow/test/sediment_config.toml"
staticmaps = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/staticmaps-moselle-sed.nc"
forcing = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/forcing-moselle-sed.nc"
instates = "https://github.com/visr/wflow-artifacts/releases/download/v1.0.0/instates-moselle-sed.nc"

# create a "data/input" directory in the current directory
testdir = @__DIR__
inputdir = joinpath(testdir, "data/input")
isdir(inputdir) || mkpath(inputdir)
toml_path = joinpath(@__DIR__, "sediment_config.toml")

# download resources to current and data dirs
download(staticmaps, joinpath(inputdir, "staticmaps-moselle-sed.nc"))
download(forcing, joinpath(inputdir, "forcing-moselle-sed.nc"))
download(instates, joinpath(inputdir, "instates-moselle-sed.nc"))
download(toml_url, toml_path)
```
