---
title: Model settings
---

This section provides an overview of model settings in the configuration TOML file, below
the `[model]` entry, including descriptions, units and default values.

## General
The Table below shows the general model settings applicable for all model types.

| Setting | Description | Unit | Default |
| --- | ----- | - | - |
| `type` | Model type: [`sbm`, `sbm_gwf`, `sediment`] | - | - |
| `cold_start__flag` | Initialize model with cold (`cold_start__flag` = `true`) or warm state | - | `true` |
| `cell_length_in_meter__flag` | Unit cell length of input rasters in lat/lon degree (`cell_length_in_meter__flag` = `false`) or in meter, cell length refers to the length of raster cells in `x` and `y` direction | - | `false` |
| `reservoir__flag` | Include reservoir modelling | - | `false` |
: {.striped .hover}

## Model types `sbm` and `sbm_gwf`
The Tables in this subsection show the available models settings for the model types `sbm` and `sbm_gwf`.

### Land Hydrology `SBM`
| Setting | Description | Unit | Default |
| ----- | ----- | -- | -- |
| `snow__flag` | Include snow modelling | - | `false` |
| `snow_gravitational_transport__flag` | Include gravitational lateral snow transport | - | `false` |
| `glacier__flag` | Include glacier modelling | - | `false` |
| `soil_infiltration_reduction__flag` | Enable reduction factor applied to the soil infiltration capacity | - | `false` |
| `soil_layer__thickness` | Thickness of soil layers | mm | [100, 300, 800] |
| `saturated_hydraulic_conductivity_profile` | Saturated hydraulic conductivity depth profile for `SBM` `soil` model (also used for kinematic wave lateral subsurface flow) | - | "exponential" |
: {.striped .hover}

### Routing method
| Setting | Description | Unit | Default |
| --- | ----- | - | - |
| `land_routing` | Routing approach for overland flow: ["kinematic-wave", "local-inertial"] | - | "kinematic-wave" |
| `river_routing` | Routing approach for river flow: ["kinematic-wave", "local-inertial"] | - | "kinematic-wave" |
: {.striped .hover}

### Kinematic wave routing
| Setting | Description | Unit | Default |
| --- | ----- | - | - |
| `pit__flag` | Include pits for kinematic wave flow continuous at subbasin only (upstream of provided pit locations)  | - | `false` |
| `river_streamorder__min_count` | Minimum stream order to delineate subbasins for river domain (for multi-threading computing purposes)  | - | 6 |
| `land_streamorder__min_count` | Minimum stream order to delineate subbasins for land domain (for multi-threading computing purposes)  | - | 5 |
| `kinematic_wave__adaptive_time_step_flag` | Enable kinematic wave adaptive (internal) time stepping  | - | `false` |
| `river_kinematic_wave__time_step` | Enable kinematic wave fixed internal time stepping for river domain (`kinematic_wave__adaptive_time_step_flag` = `false`) | s | Δt |
| `land_kinematic_wave__time_step` | Enable kinematic wave fixed internal time stepping for land domain (`kinematic_wave__adaptive_time_step_flag` = `false`) | s | Δt |
: {.striped .hover}

### Local inertial routing
| Setting | Description | Unit | Default |
| --- | ----- | - | - |
| `river_local_inertial_flow__alpha_coefficient` | Stability coefficient for internal model time step river flow routing (CFL condition) | - | 0.7 |
| `land_local_inertial_flow__alpha_coefficient` | Stability coefficient for internal model time step overland flow routing (CFL condition) | - | 0.7 |
| `land_local_inertial_flow__theta_coefficient` | Weighting factor that adjusts the amount of artificial numerical diffusion for local inertial overland flow | - | 0.8 |
| `river_water_flow_threshold__depth` | Water depth threshold for calculating river flow between cells | m | 0.001 |
| `land_surface_water_flow_threshold__depth` | Water depth threshold for calculating overland flow between cells | m | 0.001 |
| `river_water_flow__froude_limit_flag` | Limit river flow to subcritical-critical according to Froude number | - | `true` |
| `land_surface_water_flow__froude_limit_flag` | Limit overland flow to subcritical-critical according to Froude number | - | `true` |
| `floodplain_1d__flag` | Include 1D floodplain schematization for local inertial river routing | - | `false` |
: {.striped .hover}

### Groundwater flow
| Setting | Description | Unit | Default |
| --- | ----- | - | - |
| `conductivity_profile` | Hydraulic conductivity depth profile: ["uniform", "exponential"] | - | "uniform" |
| `drain__flag` | Include drainage boundary condition  | - | `false` |
| `constanthead__flag` | Include constant head boundary condition  | - | `false` |
| `subsurface_water_flow__alpha_coefficient` | Stability coefficient for internal model time step groundwater flow | - | 0.25 |
: {.striped .hover}

## Model type `sediment`
The Table below shows the model settings for the model type `sediment`.

| Setting | Description | Unit | Default |
| --- | ----- | - | - |
| `rainfall_erosion` | Rainfall erosion model: ["answers", "eurosem"]  | - | "answers" |
| `overland_flow_erosion` | Overland flow erosion model: ["answers"]  | - | "answers" |
| `run_river_model__flag` |  Include river sediment model | - | `false` |
| `land_transport` | Overland flow transport capacity method: ["yalinpart", "govers", "yalin"]  | - | "yalin" |
| `river_transport` | River flow transport capacity method: ["bagnold", "engelund", "yang", "kodatie", "molinas"]  | - | "bagnold"  |
: {.striped .hover}

