---
title: Introduction
---

This section provides an overview of all model parameters, states and variables in tables
that can be exchanged (input and output) with standard names (subsection below) for:

+ [The Land Hydrology SBM model](./parameters_landhydrology_sbm.qmd).
+ [The Land Sediment model](./parameters_sediment.qmd)
+ [Routing concepts](./parameters_routing.qmd)
+ [Water mass balance error](./parameters_massbalance.qmd)

These tables include standard names, descriptions, units and default values (input
parameters) for model parameters, states and variables. Note that a state variable can also
be specified as a model output variable but is listed only in the states table and not in in
the output table. The time unit of input flux parameters is day (the model base time step
size), hence default values for these parameters are expressed per day. During model
initialization these input parameters are converted to the user-defined model time step size
Δt.

## Standard names
The standard names of model parameters, states and variables are based on [CSDMS Standard
Names](https://csdms.colorado.edu/wiki/CSDMS_Standard_Names). These standard names are used
in the TOML configuration file and mapped to internal model parameters, states and
variables. Model output of model parameters (`[output]` section of TOML file) is not
possible by providing standard names as these are only used for setting model parameters
during model initialization, except for parameters that can also have cyclic input. These
parameters are listed in tables below "Static or cyclic/forcing input" subsections (for
[example](./parameters_landhydrology_sbm.qmd#input-cyclic-lai)). To output model parameters
and variables without a standard name one to one mapping (dot notation) can be used in the
TOML configuration file, but this is not considered as part of the public API, e.g.:

```toml
[output.netcdf_grid.variables]
land.interception.variables.canopy_storage = "canopystorage"
```

Standard names that contain `instantaneous` in the `quantity` part of the standard name can
be valid for an internal time step (for example for kinematic wave routing an internal time
step is optional (and recommended), with a time step equal to the model simulation time step
the standard name nonetheless contains `instantaneous`) and thus considered instantaneous
compared to the model simulation time step Δt $\SIb{}{s}$.

## Generic input maps {#input-generic}
The table below lists static input maps that are not directly part of wflow models and are
required to run wflow. 

| Standard Name | Description | Unit | Default value |
| ---- | ----- | - | -- |
| `basin__local_drain_direction` | Local drain direction (1-9) | - | - |
| `subbasin_location__count` | Subbasin ids | - | - |
| `river_location__mask` | River mask (0-1) | - | - |
: {.striped .hover}

For reservoir generic input see [reservoir-input](./parameters_routing.qmd#input-generic-reservoir).