---
title: Lateral concepts
---
<style>
table {
  table-layout: fixed;
  width: 100%;
}
td, th {
  word-wrap: break-word;
}
</style>

## Kinematic wave

### Surface flow
The Table below shows the parameters (fields) of struct `SurfaceFlowRiver` used for river flow,
including a description of these parameters, the unit, and default value if applicable. The
parameters in bold represent model parameters that can be set through static input data
(netCDF), and can be listed in the TOML configuration file under `[input.lateral.river]` to map
the internal model parameter to the external netCDF variable. The input parameter `slope`
(listed under `[input.lateral.river]`) is not equal to the internal model parameter `sl`, and
is listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `beta`             |  constant in Manning's equation | - | - |
| **`sl`** (`slope`) |  slope       | m m$^{-1}$| - |
| **`n`**         | Manning's roughness | s m$^{-\frac{1}{3}}$| 0.036 |
| **`dl`**        |  length      | m     |  -      |
| `q`             | discharge     | m$^3$ s$^{-1}$| - |
| `qin`           | inflow from upstream cells | m$^3$ s$^{-1}$| - |
| `q_av`          | average discharge | m$^3$ s$^{-1}$| - |
| `qlat`          | lateral inflow per unit length  | m$^2$ s$^{-1}$| - |
| `inwater`       | lateral inflow | m$^3$ s$^{-1}$| - |
| **`inflow`**    | external inflow (abstraction/supply/demand) | m$^3$ s$^{-1}$| 0.0 |
| `inflow_wb`     | inflow waterbody (lake or reservoir model) from land part | m$^3$ s$^{-1}$| 0.0 |
| `abstraction`   | abstraction (computed as part of water demand and allocation) | m$^3$ s$^{-1}$| 0.0 |
| `volume`        | kinematic wave volume |m$^3$| - |
| `h`             | water level | m | - |
| `h_av`          | average water level | m | - |
| **`bankfull_depth`**   | bankfull river depth  | m | 1.0 |
| `dt`            | model time step | s | - |
| `its`           | number of fixed iterations | - | - |
| **`width`**     |  width       | m          | - |
| `alpha_pow`     | used in the power part of $\alpha$ | - | - |
| `alpha_term`    | term used in computation of $\alpha$ | - | - |
| `alpha`             | constant in momentum equation $A = \alpha Q^{\beta}$ | s$^{\frac{3}{5}}$ m$^{\frac{1}{5}}$ | - |
| `cel`           | celerity of kinematic wave | m s$^{-1}$ | - |
| `reservoir_index`   |  map cell to 0 (no reservoir) or i (pick reservoir i in reservoir field) | - | - |
| `lake_index`   |  map cell to 0 (no lake) or i (pick lake i in lake field) | - | - |
| `reservoir`    | an array of reservoir models `SimpleReservoir` | - | - |
| `lake`         | an array of lake models `Lake` | - | - |
| `allocation`| water allocation of type `AllocationRiver` | - | - |
| `kinwave_it`   | boolean for kinematic wave iterations | - | false |
: {.striped .hover}

The Table below shows the parameters (fields) of struct `SurfaceFlowLand` used for overland
flow, including a description of these parameters, the unit, and default value if applicable.
The parameters in bold represent model parameters that can be set through static input data
(netCDF), and can be listed in the TOML configuration file under `[input.lateral.land]` to map
the internal model parameter to the external netCDF variable. The input parameter `slope`
(listed under `[input.lateral.land]`) is not equal to the internal model parameter `sl`, and is
listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `beta`             |  constant in Manning's equation | - | - |
| **`sl`** (`slope`) |  slope       | m m$^{-1}$| - |
| **`n`**         | Manning's roughness | s m$^{-\frac{1}{3}}$| 0.072 |
| `dl`            |  length      | m     |  -      |
| `q`             | discharge     | m$^3$ s$^{-1}$| - |
| `qin`           | inflow from upstream cells | m$^3$ s$^{-1}$| - |
| `q_av`          | average discharge | m$^3$ s$^{-1}$| - |
| `qlat`          | lateral inflow per unit length  | m$^2$ s$^{-1}$| - |
| `inwater`       | lateral inflow | m$^3$ s$^{-1}$| - |
| `volume`        | kinematic wave volume |m$^3$| - |
| `h`             | water level | m | - |
| `h_av`          | average water level | m | - |
| `dt`            | model time step | s | - |
| `its`           | number of fixed iterations | - | - |
| `width`         |  width       | m          | - |
| `alpha_pow`     | used in the power part of $\alpha$ | - | - |
| `alpha_term`    | term used in computation of $\alpha$ | - | - |
| `alpha`             | constant in momentum equation $A = \alpha Q^{\beta}$ | s$^{\frac{3}{5}}$ m$^{\frac{1}{5}}$ | - |
| `cel`           | celerity of kinematic wave | m s$^{-1}$ | - |
| `to_river`      | part of overland flow that flows to the river | m$^3$ s$^{-1}$ | - |
| `kinwave_it`    | boolean for kinematic wave iterations | - | false |
: {.striped .hover}

### Lateral subsurface flow
The Table below shows the parameters (fields) of struct `LateralSSF`, including a description
of these parameters, the unit, and default value if applicable. The parameters in bold
represent model parameters that can be set through static input data (netCDF). The soil related
parameters `f`, `soilthickness`, `z_exp`, `theta_s` and `theta_r` are derived from the vertical
`SBM` concept (including unit conversion for `f`, `z_exp` and `soilthickness`), and can be
listed in the TOML configuration file under `[input.vertical]`, to map the internal model
parameter to the external netCDF variable. The internal slope model parameter `slope` is set
through the TOML file as follows:

```toml
[input.lateral.land]
slope = "Slope"
```

The parameter `kh_0` is computed by multiplying the vertical hydraulic conductivity at the soil
surface `kv_0` (including unit conversion) of the vertical `SBM` concept with the internal
parameter `khfrac` \[-\] (default value of 1.0). The internal model parameter `khfrac` is set
through the TOML file as follows:

```toml
[input.lateral.subsurface]
ksathorfrac = "KsatHorFrac"
```

The `khfrac` parameter compensates for anisotropy, small scale `kv_0` measurements (soil core)
that do not represent larger scale hydraulic conductivity, and smaller flow length scales
(hillslope) in reality, not represented by the model resolution.

For the vertical [SBM](./parameters_vertical.qmd#sbm) concept different vertical hydraulic
conductivity depth profiles are possible, and these also determine which `LateralSSF`
parameters are used including the input requirements for the computation of lateral subsurface
flow. For the `exponential` profile the model parameters `kh_0` and `f` are used. For the
`exponential_constant` profile `kh_0` and `f` are used, and `z_exp` is required as part of
`[input.vertical]`. For the `layered` profile, `SBM` model parameter `kv` is used, and for the
`layered_exponential` profile `kv` is used and `z_exp` is required as part of
`[input.vertical]`.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `kh_0`          | horizontal hydraulic conductivity at soil surface  | m d$^{-1}$ |  3.0 |
| **`f`** | a scaling parameter (controls exponential decline of `kh_0`) | m$^{-1}$  | 1.0 |
| `kh` | horizontal hydraulic conductivity | m d$^{-1}$  | - |
| **`khfrac`** (`ksathorfrac`) | a muliplication factor applied to vertical hydraulic conductivity `kv` | -  | 100.0 |
| **`soilthickness`** | soil thickness | m  | 2.0 |
| **`theta_s`** | saturated water content (porosity) | -  | 0.6 |
| **`theta_r`** | residual water content  | -  | 0.01 |
| `dt` | model time step | d  | - |
| **`slope`** | slope | m m$^{-1}$  | - |
| `dl` | drain length | m | - |
| `dw` | drain width | m | - |
| `zi` | pseudo-water table depth (top of the saturated zone) | m | - |
| **`z_exp`** | depth from soil surface for which exponential decline of `kh_0` is valid | m | - |
| `exfiltwater` | exfiltration (groundwater above surface level, saturated excess conditions) | m Δt⁻¹ | - |
| `recharge` | net recharge to saturated store  | m$^2$ Δt⁻¹ | - |
| `ssf` | subsurface flow  | m$^3$ d${-1}$  | - |
| `ssfin` | inflow from upstream cells | m$^3$ d${-1}$  | - |
| `ssfmax` | maximum subsurface flow | m$^2$ d${-1}$  | - |
| `to_river` | part of subsurface flow that flows to the river | m$^3$ d${-1}$  | - |
| `volume` | subsurface water volume | m$^3$ | - |

## Local inertial

### River flow
The Table below shows the parameters (fields) of struct `ShallowWaterRiver`, including a
description of these parameters, the unit, and default value if applicable. The parameters in
bold represent model parameters that can be set through static input data (netCDF), and can be
listed in the TOML configuration file under `[input.lateral.river]`, to map the internal model
parameter to the external netCDF variable. The parameter river bed elevation `zb` is based on
the bankfull elevation and depth input data:

```toml
[input.lateral.river]
bankfull_elevation = "RiverZ"
bankfull_depth = "RiverDepth"
```

When floodplain routing (parameter `floodplain`) is included as part of local inertial river
flow, parameter `q_av` represents the total average discharge of the river channel and
floodplain routing, and parameter `q_channel_av` represents average river channel discharge.
Otherwise parameters `q_av` and `q_channel_av` represent both average river channel discharge
(are equal).

The input parameter `n` (listed under `[input.lateral.river]`) is not equal to the internal
model parameter `mannings_n`, and is listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| **`mannings_n`** (`n`) |  Manning's roughness | s m$^{-\frac{1}{3}}$ | 0.036 |
| **`width`**    |  river width | m | - |
| `zb`    |  river bed elevation | m | - |
| **`length`**    |  river length | m | - |
| `n`   |  number of cells | - | - |
| `ne`    |  number of edges/links | - | - |
| `active_n`    |  active nodes | - | - |
| `active_e`    |  active edges | - | - |
| `g`    |  acceleration due to gravity | m s$^{-2}$ | - |
| `alpha`    |  stability coefficient (Bates et al., 2010) | - | 0.7 |
| `h_thresh`    |  depth threshold for calculating flow | m | 0.001 |
| `dt`    |  model time step | s | - |
| `q`    |  river discharge (subgrid channel) | m$^3$ s$^{-1}$ | - |
| `q_av`    |  average river channel (+ floodplain) discharge | m$^3$ s$^{-1}$ | - |
| `q_channel_av` | average river channel discharge | m$^3$ s$^{-1}$ | - |
| `zb_max`    | maximum channel bed elevation | m | - |
| `mannings_n_sq` | Manning's roughness squared at edge/link | (s m$^{-\frac{1}{3}}$)$^2$ | - |
| `h`    | water depth | m | - |
| `zs_max`    | maximum water elevation | m | - |
| `zs_src`    | water elevation of source node of edge | m | - |
| `zs_dst`    | water elevation of downstream node of edge | m | - |
| `hf`    | water depth at edge/link | m | - |
| `h_av`    | average water depth | m | - |
| `dl`    | river length | m | - |
| `dl_at_link`    | river length at edge/link | m | - |
| `width`    | river width | m | - |
| `width_at_link`    | river width at edge/link | m | - |
| `a`    | flow area at edge/link | m$^2$ | - |
| `r`    | hydraulic radius at edge/link | m | - |
| `volume`    | river volume | m$^3$ | - |
| `error`    | error volume | m$^3$ | - |
| `inwater`    | lateral inflow | m$^3$ s$^{-1}$ | - |
| **`inflow`**  | external inflow (abstraction/supply/demand) | m$^3$ s$^{-1}$| 0.0 |
| `abstraction` | abstraction (computed as part of water demand and allocation) | m$^3$ s$^{-1}$| 0.0 |
| `inflow_wb`        | inflow waterbody (lake or reservoir model) from land part | m$^3$ s$^{-1}$| 0.0 |
| `bankfull_volume`    | bankfull volume | m$^3$ | - |
| **`bankfull_depth`**    | bankfull depth | m | - |
| `froude_limit`    | if true a check is performed if froude number > 1.0 (algorithm is modified) | - | - |
| `reservoir_index`   |  river cell index with a reservoir | - | - |
| `lake_index`   |  river cell index with a lake | - | - |
| `waterbody`   |  water body cells (reservoir or lake) | - | - |
| `reservoir`    | an array of reservoir models `SimpleReservoir` | - | - |
| `lake` | an array of lake models `Lake` | - | - |
| `allocation`| optional water allocation of type `AllocationRiver` | - | - |
| `floodplain` | optional 1D floodplain routing `FloodPlain` | - | - |
: {.striped .hover}

### 1D floodplain
The Table below shows the parameters (fields) of struct `FloodPlain` (part of struct
`ShallowWaterRiver`), including a description of these parameters, the unit, and default value
if applicable. The parameters in bold represent model parameters that can be set through static
input data (netCDF), and can be listed in the TOML configuration file under
`[input.lateral.river.floodplain]`, to map the internal model parameter to the external netCDF
variable. The input parameter `n` (listed under `[input.lateral.river.floodplain]`) is not
equal to the internal model parameter `mannings_n`, and is listed in the Table below between
parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| **`profile`**   |  Floodplain profile `FloodPlainProfile` | | |
| **`mannings_n`** (`n`)    |  Manning's roughness for the floodplain | s m$^{-\frac{1}{3}}$ | 0.072 |
| `mannings_n_sq` | Manning's roughness squared at edge/link | (s m$^{-\frac{1}{3}}$)$^2$ | - |
| `volume`    | flood volume | m$^3$ | - |
| `h`    | flood depth | m | - |
| `h_av`    | average flood depth | m | - |
| `error` | | error volume | m$^3$ | - |
| `a`    | flow area at edge/link | m$^2$ | - |
| `r`    | hydraulic radius at edge/link | m | - |
| `hf`    | flood depth at edge/link | m | - |
| `zb_max` | maximum bankfull elevation at edge | m | - |
| `q0`  |  discharge at previous time step| m$^3$ s$^{-1}$ | - |
| `q`    |  discharge | m$^3$ s$^{-1}$ | - |
| `q_av`    |  average discharge | m$^3$ s$^{-1}$ | - |
| `hf_index` |  index with `hf` above depth threshold | - | - |
: {.striped .hover}

The floodplain profile `FloodPlainProfile` contains the following parameters:

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| **`depth`** (`flood_depth`) |  flood depths | m | - |
| **`volume`**    |  cumulative flood volume (per flood depth) | m$^3$ | - |
|  `width`   |  cumulative floodplain width (per flood depth) | m | - |
|  `a`   |  cumulative floodplain flow area (per flood depth) | m$^2$ | - |
|  `p`   |  cumulative floodplain wetted perimeter (per flood depth) | m | - |
: {.striped .hover}

The floodplain volumes (per flood `depth` interval) can be set as follows through the TOML
file:

```toml
[input.lateral.river.floodplain]
volume = "floodplain_volume"
```

The input parameter `flood_depth` (dimension of floodplain `volume`) is not equal to the
internal model parameter `depth`, and is listed in the Table below between parentheses.

### Overland flow
The Table below shows the parameters (fields) of struct `ShallowWaterLand`, including a
description of these parameters, the unit, and default value if applicable. The parameters in
bold represent model parameters that can be set through static input data (netCDF), and can be
listed in the TOML configuration file under `[input.lateral.land]`, to map the internal model
parameter to the external netCDF variable.

The mannings roughness (for the computation of `mannings_n_sq`) should be provided as follows
in the TOML file:

```toml
[input.lateral.land]
n = "n_land" # mannings roughness
```

The input parameter `elevation` (listed under `[input.lateral.land]`) is not equal to the
internal model parameter `z`, and is listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `n`    |  number of cells | - | - |
| `xl`| cell length x direction | m | - |
| `yl`| cell length y direction | m | - |
| `xwidth`| effective flow width x direction (floodplain) | m | - |
| `ywidth`| effective flow width y direction (floodplain) | m | - |
| `g` | acceleration due to gravity | m s$^{-2}$ | - |
| `theta` | weighting factor (de Almeida et al., 2012) | - | 0.8 |
| `alpha`    |  stability coefficient (Bates et al., 2010) | - | 0.7 |
| `h_thresh`    |  depth threshold for calculating flow | m | 0.001 |
| `dt`   |  model time step| s | - |
| `qy0`  |  flow in y direction at previous time step| m$^3$ s$^{-1}$ | - |
| `qx0`  |  flow in x direction at previous time step| m$^3$ s$^{-1}$ | - |
| `qx`  |  flow in x direction | m$^3$ s$^{-1}$ | - |
| `qy`  |  flow in y direction | m$^3$ s$^{-1}$ | - |
| `zx_max`  |  maximum cell elevation (x direction) | m | - |
| `zy_max`  |  maximum cell elevation (y direction) | m | - |
| `mannings_n_sq` |  Manning's roughness squared | s m$^{-\frac{1}{3}}$ | based on 0.072 |
| `volume`  |  total volume of cell (including river volume for river cells) | m$^3$ | - |
| `error`  |  error volume | m$^3$ | - |
| `runoff`  |  runoff from hydrological model | m$^3$ s$^{-1}$ | - |
| `h` |  water depth of cell | m | - |
| **`z`** (`elevation`)  |  elevation of cell | m | - |
| `froude_limit`  |  if true a check is performed if froude number > 1.0 (algorithm is modified)| - | - |
| `rivercells`  |  river cells| - | - |
| `h_av` | average water depth| m | - |

## Water bodies

### Reservoirs
The Table below shows the parameters (fields) of struct `SimpleReservoir`, including a
description of these parameters, the unit, and default value if applicable. The parameters in
bold represent model parameters that can be set through static input data (netCDF), and can be
listed in the TOML configuration file under `[input.lateral.river.reservoir]`, to map the
internal model parameter to the external netCDF variable.

Two parameters reservoir coverage `areas` and the outlet of reservoirs (unique id) `locs` that
are not part of the `SimpleReservoir` struct are also required, and can be set as follows
through the TOML file:

```toml
[input.lateral.river.reservoir]
areas = "wflow_reservoirareas"
locs = "wflow_reservoirlocs"
```

|  parameter | description  	        | unit | default |
|:---------------| --------------- | ---------------------- | ----- |
| **`area`**        | area | m``^2`` | - |
| **`demand`**  | minimum (environmental) flow requirement downstream of the reservoir | m``^3`` s``^{-1}``| - |
| **`maxrelease`** | maximum amount that can be released if below spillway | m``^3`` s``^{-1}`` | - |
| **`maxvolume`** | maximum storage (above which water is spilled) | m``^3`` | - |
| **`targetfullfrac`** | target fraction full (of max storage)| -        | - |
| **`targetminfrac`** | target minimum full fraction (of max storage) | -  | - |
| `demandrelease`| minimum (environmental) flow released from reservoir  | m``^3`` s``^{-1}``| - |
| `dt`             | model time step     | s | - |
| `volume`             | volume     | m``^3`` | - |
| `inflow`             | total inflow into reservoir | m``^3`` | - |
| `outflow`             | outflow of reservoir | m``^3`` s``^{-1}`` | - |
| `totaloutflow`        | total outflow of reservoir | m``^3`` | - |
| `percfull`             | fraction full (of max storage) | - | - |
| `precipitation`             | average precipitation for reservoir area | mm Δt⁻¹ | - |
| `evaporation`             | average potential evaporation for reservoir area | mm Δt⁻¹ | - |
| `actevap` | average actual evaporation for lake area | mm Δt⁻¹  | - |

### Lakes
The Table below shows the parameters (fields) of struct `Lake`, including a description of
these parameters, the unit, and default value if applicable. The parameters in bold
represent model parameters that can be set through static input data (netCDF), and can be
listed in the TOML configuration file under `[input.lateral.river.lake]`, to map the
internal model parameter to the external netCDF variable.

Two parameters lake coverage `areas` and the outlet of lakes (unique id) `locs` that are not
part of the `Lake` struct are also required, and can be set as follows through the
TOML file:

```toml
[input.lateral.river.lake]
areas = "wflow_lakeareas"
locs = "wflow_lakelocs"
```

The input parameter `linkedlakelocs` (listed under `[input.lateral.river.lake]`) is not
equal to the internal model parameter `lowerlake_ind`, and is listed in the Table below
between parentheses.

|  parameter | description  	        | unit | default |
|:---------------| --------------- | ---------------------- | ----- |
| **`area`**         | area| m``^2`` | - |
| **`b`**       | Rating curve coefficient  | - | - |
| **`e`**      | Rating curve exponent | -  | - |
| **`outflowfunc`**     | type of lake rating curve | - | - |
| **`storfunc`** | type of lake storage curve| - | - |
| **`threshold`**  | water level threshold ``H_0`` below that level outflow is zero | m  | - |
| **`waterlevel`**  | waterlevel ``H`` of lake | m  | - |
| **`lowerlake_ind`** (`linkedlakelocs`) | Index of lower lake (linked lakes) | - | 0 |
| **`sh`** | data for storage curve | - | - |
| **`hq`** | data rating curve | - | - |
| `dt`             | model time step     | s |  - |
| `inflow` | total inflow to the lake | m``^3``  | - |
| `storage` | storage lake | m``^3``  | - |
| `maxstorage`| maximum storage lake with rating curve type 1 | m``^3``  | - |
| `outflow` | outflow lake | m``^3`` s``^{-1}``  | - |
| `totaloutflow` | total outflow lake | m``^3``  | - |
| `precipitation` | average precipitation for lake area | mm Δt⁻¹  | - |
| `evaporation` | average potential evaporation for lake area | mm Δt⁻¹  | - |
| `actevap` | average actual evaporation for lake area | mm Δt⁻¹  | - |


## Water allocation river
The Table below shows the parameters (fields) of struct `AllocationRiver`, used when water
demand and allocation is computed (optional), including a description of these parameters, the
unit, and default value if applicable.

|  parameter  | description  	  | unit  | default |
|:--------------- | ------------------| ----- | -------- |
| `act_surfacewater_abst` |  actual surface water abstraction | mm Δt⁻¹ | - |
| `act_surfacewater_abst_vol`| actual surface water abstraction | m$^3$ Δt⁻¹ | - |
| `available_surfacewater`| available surface water | m$^3$ | - |
| `nonirri_returnflow`| return flow from non-irrigation (industry, domestic and livestock) | mm Δt⁻¹ | - |

## Groundwater flow

### Confined aquifer
The Table below shows the parameters (fields) of struct `ConfinedAquifer`, including a
description of these parameters, the unit, and default value if applicable. Struct
`ConfinedAquifer` is not (yet) part of a wflow model.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `k` | horizontal conductivity  | m d$^{-1}$s | - |
| `storativity`     | storativity  | m m$^{-1}$ | - |
| `specific_storage` | specific storage | m$^{-1}$ | - |
| `top`     | top groundwater layers  | m | - |
| `bottom`     | bottom groundwater layers  | m | - |
| `area`          | cell area    | m$^2$ | - |
| `head`          | groundwater head     | m | - |
| `conductance`          | conductance    | m$^2$ d$^{-1}$ | - |
: {.striped .hover}

### Unconfined aquifer
The Table below shows the parameters (fields) of struct `UnconfinedAquifer`, including a
description of these parameters, the unit, and default value if applicable. The parameters in
bold represent model parameters that can be set through static input data (netCDF), and can be
listed in the TOML configuration file under `[input.lateral.subsurface]`, to map the internal
model parameter to the external netCDF variable. For some input parameters the parameter listed
under `[input.lateral.subsurface]` is not equal to the internal model parameter, these are
listed in the Table below between parentheses after the internal model parameter. The `top`
parameter is provided by the external parameter `altitude` as part of the static input data and
set as follows through the TOML file:

```toml
[input]
# these are not directly part of the model
altitude = "wflow_dem"
```

The input parameter `conductivity` (listed under `[input.lateral.subsurface]`) is not equal to
the internal model parameter `kh_0`, and is listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| **`kh_0`** (`conductivity`) | horizontal conductivity  | m d$^{-1}$s | - |
| **`specific_yield`**    | specific yield  | m m$^{-1}$ | - |
| **`top`** (`altitude`)  | top groundwater layer  | m | - |
| `bottom`     | bottom groundwater layer  | m | - |
| `area`          | cell area    | m$^2$ | - |
| `head`          | groundwater head     | m | - |
| `conductance`          | conductance    | m$^2$ d$^{-1}$ | - |
| `f` | factor controlling the reduction of reference horizontal conductivity | - | 3.0 |
: {.striped .hover}

### Constant Head
The Table below shows the parameters (fields) of struct `ConstantHead`, including a description
of these parameters, the unit, and default value if applicable. The parameters in bold
represent model parameters that can be set through static input data (netCDF), and can be
listed in the TOML configuration file under `[input.lateral.subsurface]`, to map the internal
model parameter to the external netCDF variable. The input parameter `constant_head` (listed
under `[input.lateral.subsurface]`) is not equal to the internal model parameter `head`, and is
listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| **`head`** (`constant_head`)          | groundwater head     | m | - |
| `index`          | constant head cell index | - | - |
: {.striped .hover}

### Boundary conditions

#### River
The Table below shows the parameters (fields) of struct `River`, including a description of
these parameters, the unit, and default value if applicable. The parameters in bold represent
model parameters that can be set through static input data (netCDF), and can be listed in the
TOML configuration file under `[input.lateral.subsurface]`, to map the internal model parameter
to the external netCDF variable. The input parameter `river_bottom` (listed under
`[input.lateral.subsurface]`) is not equal to the internal model parameter `bottom`, and is
listed in the Table below between parentheses.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `stage`    | river stage  | m | - |
| **`infiltration_conductance`**     | river bed infiltration conductance  | m$^2$ day$^{-1}$ m$^2$ day$^{-1}$| - |
| **`exfiltration_conductance`**     | river bed exfiltration conductance   | m$^2$ day$^{-1}$ | - |
| **`bottom`** (`river_bottom`)     | river bottom elevation  | m | - |
| `index`         |  river cell index | - | - |
| `flux`          | exchange flux (river to aquifer)  | m$^3$ d$^{-1}$ | - |
: {.striped .hover}

#### Drainage
The Table below shows the parameters (fields) of struct `Drainage`, including a description of
these parameters, the unit, and default value if applicable. The parameters in bold represent
model parameters that can be set through static input data (netCDF), and can be listed in the
TOML configuration file under `[input.lateral.subsurface]`, to map the internal model parameter
to the external netCDF variable. For some input parameters the parameter listed under
`[input.lateral.subsurface]` is not equal to the internal model parameter, these are listed in
the Table below between parentheses after the internal model parameter.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| **`elevation`** (`drain_elevation`)   | drain elevation  | m | - |
| **`conductance`** (`drain_conductance`)  | drain conductance  | m$^2$ day$^{-1}$ | - |
| **`index`** (`drain`) |  drain cell index | - | - |
| `flux`          | exchange flux (drains to aquifer)  | m$^3$ day$^{-1}$ | - |
: {.striped .hover}

#### Recharge
The Table below shows the parameters (fields) of struct `Recharge`, including a description of
these parameters, the unit, and default value if applicable.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `rate`          | recharge rate  | m$^3$ day$^{-1}$ | - |
| `index`         |  recharge cell index | - | - |
| `flux`          | recharge flux  | m$^3$ day$^{-1}$ | - |
: {.striped .hover}

#### Head boundary
The Table below shows the parameters (fields) of struct `HeadBoundary`, including a description
of these parameters, the unit, and default value if applicable.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `head`          | head  | m | - |
| `conductance`   |  conductance of the head boundary  | m$^2$ day$^{-1}$ | - |
| `index`         |  head boundary cell index | - | - |
| `flux`          |  conductance of the head boundary  | m$^3$ day$^{-1}$ | - |
: {.striped .hover}

#### Well boundary
The Table below shows the parameters (fields) of struct `Well`, including a description of
these parameters, the unit, and default value if applicable.

| Parameter | Description | Unit | Default |
|:----| -------- | ---- | ---- |
| `volumetric_rate` | volumetric well rate  | m$^3$ d$^{-1}$ | - |
| `index` | well index  | - | - |
| `flux`          |  actual well flux  | m$^3$ day$^{-1}$ | - |
: {.striped .hover}





## Lakes
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `lake_location__count` | Lake outlet locations (physical location in the model) | - | - |
| `lake_area__count` | Lake mask (cells covered by the lake) | - | - |
| `lake_surface__area` | Area of the lake | m² | - |
| `lake_water__rating_curve_coefficient` | Rating curve coefficient | - | - |
| `lake_water__rating_curve_exponent` | Rating curve exponent | - | - |
| `lake_water_flow_threshold-level__elevation` | Water level threshold, below this level outflow is zero | m | - |
| `lake~lower_location__count` | Index of lower lake (linked lakes) | - | 0 |
| `lake_water__storage_curve_type_count` | Type of lake storage curve | - | - |
| `lake_water__rating_curve_type_count` | Type of lake rating curve | - | - |
| `lake_water_level__initial_elevation` | Water level of lake (used for initialization) | m | - |
: {.striped .hover}

### States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `lake_water_surface__instantaneous_elevation` | Lake water level (at the last internal timestep) | m |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `lake_water__volume` | Lake volume | m³ |
| `lake_water_surface__elevation` | Lake water level (average over timestep) | m |
| `lake_water~outgoing__volume_flow_rate` | Outflow of the lake | m³ s⁻¹ |
| `lake_water~incoming__volume_flow_rate` | Inflow into the lake | m³ s⁻¹ |
| `lake_water__evaporation_volume_flux` | Average actual evaporation over the lake area | mm Δt⁻¹ |
| `lake_water__precipitation_volume_flux` | Average precipitation over the lake area | mm Δt⁻¹ |
| `lake_water__potential_evaporation_volume_flux` | Average potential evaporation over the lake area | mm Δt⁻¹ |
: {.striped .hover}

## Reservoirs
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `reservoir_location__count` | Reservoir outlet locations (physical location in the model) | - | - |
| `reservoir_area__count` | Reservoir area (cells covered by the lake) | - | - |
| `reservoir_surface__area` | Area of the reservoir | m² | - |
| `reservoir_water_demand~required~downstream__volume_flow_rate` | Minimum (environmental) flow released from reservoir | m³ s⁻¹ | - |
| `reservoir_water_release-below-spillway__max_volume_flow_rate` | Maximum amount that can be released if below spillway | m³ s⁻¹ | - |
| `reservoir_water__max_volume` | Maximum volume (above which water is spilled) | m³ | - |
| `reservoir_water~full-target__volume_fraction` | Target fraction full (of max storage) | - | - |
| `reservoir_water~min-target__volume_fraction` | Target minimum full fraction (of max storage)	| - | - |
: {.striped .hover}

### States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `reservoir_water__instantaneous_volume` | Reservoir volume (at the last internal timestep) | m³ |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `reservoir_water__volume` | Reservoir volume (average over the timestep) | m³ |
| `reservoir_water~outgoing__volume_flow_rate` | Outflow of the reservoir | m³ s⁻¹ |
| `reservoir_water~incoming__volume_flow_rate` | Inflow into the reservoir | m³ s⁻¹ |
| `reservoir_water__evaporation_volume_flux` | Average actual evaporation over the reservoir area | mm Δt⁻¹ |
| `reservoir_water__precipitation_volume_flux` | Average precipitation over the reservoir area | mm Δt⁻¹ |
| `reservoir_water__potential_evaporation_volume_flux` | Average potential evaporation over the reservoir area | mm Δt⁻¹ |
: {.striped .hover}

## Subsurface flow


### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `subsurface_water__horizontal-to-vertical_saturated_hydraulic_conductivity_ratio` | A muliplication factor applied to vertical hydraulic conductivity | - | 100 |
: {.striped .hover}

### States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `subsurface_water__volume_flow_rate` | Subsurface flow | m³ day⁻¹ |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `subsurface_water__volume_flow_rate` | Subsurface flow | m³ day⁻¹ |
| `subsurface_water_sat-zone_top__net_recharge_volume_flow_rate` | net recharge to saturated store (only for `sbm_gwf`??) | m³ day⁻¹ |
: {.striped .hover}

## Kinematic wave (river)


### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `river_water_flow__manning_n_parameter` | Manning’s roughness | s m$^{-\frac{1}{3}}$ | 0.0036 |
| `river_bank_water__depth` | Bankfull river depth | m | 1.0 |
| `river__slope` | River slope | m m⁻¹ | - |
: {.striped .hover}

### States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `river_water__instantaneous_volume_flow_rate` | Discharge (at the end of internal timesep) | m³ s⁻¹ |
| `river_water__instantaneous_depth` | Water level (at the end of internal timestep) | m |
| `river_water__depth` | Water lavel (average over timestep) | m |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `river_water__volume_flow_rate` | Discharge | m³ s⁻¹ |
| `river_water__depth` | Water level | m |
| `river_water__volume` | River water volume | m³ |
: {.striped .hover}

## Kinematic wave (overland flow)
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `land_surface_water_flow__manning_n_parameter` | Manning’s roughness | s m$^{-\frac{1}{3}}$ | 0.072 |
: {.striped .hover}

### States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `land_surface_water__instantaneous_volume_flow_rate` | Discharge (at the end of internal timesep) | m³ s⁻¹ |
| `land_surface_water__instantaneous_depth` | Water level (at the end of internal timestep) | m |
| `land_surface_water__depth` | Water lavel (average over timestep) | m |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `land_surface_water__volume_flow_rate` | Discharge | m³ s⁻¹ |
| `land_surface_water__depth` | Water level | m |
| `land_surface_water__volume` | River water volume | m³ |
: {.striped .hover}

## Local inertial (river)


### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `model_boundary_condition~river__length` | Distance from last river pixel where boundary condition is applied | m | 10 000 |
| `model_boundary_condition~river_bank_water__depth` | Boundary condition after the last river pixel | m | 0.0 |
| `river_bank_water__elevation` | Elevation of the river (excluding depth) | m | - |
| `river_bank_water__depth` | Bankfull depth of the river | m | - |
| `river_water_flow__manning_n_parameter` | Manning’s roughness | s m$^{-\frac{1}{3}}$ | 0.0036 |
: {.striped .hover}

## Local inertial (land)


### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `land_surface_water_flow__manning_n_parameter` | Manning’s roughness | s m$^{-\frac{1}{3}}$ | 0.072 |
| `land_surface_water_flow__ground_elevation` | Elevation of each cell | m | - |
: {.striped .hover}

### States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `land_surface_water__x_component_of_instantaneous_volume_flow_rate` | Flow in x direction (value at end of internal timestep) | m³ s⁻¹ |
| `land_surface_water__y_component_of_instantaneous_volume_flow_rate` | Flow in y direction (value at end of internal timestep) | m³ s⁻¹ |
| `land_surface_water__instantaneous_depth` | Water level (value at end of internal timestep) | m |
| `land_surface_water__depth` | Waterlevel (average over timestep) | m |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `land_surface_water__x_component_of_instantaneous_volume_flow_rate` | Flow in x direction (value at end of internal timestep) | m³ s⁻¹ |
| `land_surface_water__y_component_of_instantaneous_volume_flow_rate` | Flow in y direction (value at end of internal timestep) | m³ s⁻¹ |
| `land_surface_water__depth` | Waterlevel (average over timestep) | m |
: {.striped .hover}

## Local inertial (1D floodplains)

### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `floodplain_water__sum_of_volume-per-depth` | Floodplain profile (volume per water level above river) | m³ | - |
| `floodplain_water_flow__manning_n_parameter` | Manning’s roughness | s m$^{-\frac{1}{3}}$ | 0.072 |
: {.striped .hover}

### States
| Standard Name | Description | Unit | |
| --- | ---- | - |
| `floodplain_water__instantaneous_volume_flow_rate` | Discharge in the floodplain (value at end of internal timestep) | m³ s⁻¹ |
| `floodplain_water__instantaneous_depth` | Waterlevel in the floodplain (value at end of internal timestep) | m |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `floodplain_water__volume` | Volume of water in the floodplain | m³ |
| `floodplain_water__volume_flow_rate` | Discharge in the floodplain (average over timestep) | m³ s⁻¹ |
: {.striped .hover}

# wflow_sbm+gwf specifics


## Unconfined aquifer
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `subsurface_surface_water__horizontal_saturated_hydraulic_conductivity` | Horizontal conductivity | m day⁻¹ | - |
| `subsurface_water__specific_yield` | Specific yield | m m⁻¹ | - |
| `subsurface__horizontal_saturated_hydraulic_conductivity_scale_parameter` | Factor controlling the reduction of horizontal conductivity with depth | - | 3.0 |
: {.striped .hover}

## States
| Standard Name | Description | Unit |
| --- | ---- | - |
| `subsurface_water__hydraulic_head` | Groundwater head | m |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `subsurface_water__hydraulic_head` | Groundwater head | m |
: {.striped .hover}

## River boundary
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `river_water__infiltration_conductance` | River bed infiltration conductance | m² day⁻¹ | - |
| `river_water__exfiltration_conductance` | River bed exfiltration conductance | m² day⁻¹ | - |
| `river_bottom__elevation` | River bottom elevation | m | - |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `river_water~to-subsurface__volume_flow_rate` | Exchange flux (river to aquifer) | m³ day⁻¹ |
: {.striped .hover}

## Drainage boundary
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `land_drain__elevation` | Drain elevation | m | - |
| `land_drain__conductance` | Drain conductance | m² day⁻¹ | - |
| `land_drain_location__flag` | Drain locations | - | - |
: {.striped .hover}

### Output
| Standard Name | Description | Unit |
| --- | ---- | - |
| `land_drain_water~to-subsurface__volume_flow_rate` | Exchange flux (drain to aquifer) | m³ day⁻¹ |
: {.striped .hover}

## Constant head boundary
### Input
| Standard Name | Description | Unit | Default |
| --- | ---- | - | - |
| `model_boundary_condition~constant_hydraulic_head` | Head of the boundary | m | - |
: {.striped .hover}