name: CompatHelper
on:
  schedule:
    - cron: 47 11 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          import CompatHelper
          CompatHelper.main(;
              subdirs=["Wflow"],
              bump_compat_containing_equality_specifier=false,
          )
        shell: julia --color=yes {0}
