name: Parameter & variable metadata JSON generation
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "Wflow/src/standard_name/**" ]
  pull_request:
    paths: [ "Wflow/src/standard_name/**" ]
jobs:
  json_gen:
    name: JSON generation
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: julia-actions/cache@a7bed9df697e5d7309d68afe7542a87621a8b6c8 # v3.3.0
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      - name: Test parameter metadata JSON generation
        run: |
          pixi run parameter_metadata_json_gen
          pixi run fix-check
      - name: Ensure that there was no change in the metadata
        run: git diff --exit-code
