name: Trivy Security Scan
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  trivy_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required to checkout and read repo files
      security-events: write # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          sarif_file: "trivy-results.sarif"
