name: Trivy Security Scan
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  trivy_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required to checkout and read repo files
      security-events: write # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "config"
          hide-progress: true
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"
